<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InternalsVisibleTo>RemoteCmd.Tests</InternalsVisibleTo>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RemoteCmd.Tests" />
    <InternalsVisibleTo Include="RemoteCmd.IntegrationTests" />
  </ItemGroup>

</Project>
